# Generated by Django 2.0.2 on 2018-06-16 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_post_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='profile_image',
            new_name='postImage',
        ),
    ]
