# Generated by Django 2.0.2 on 2018-06-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20180616_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='passwd',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
