# Generated by Django 2.0.2 on 2018-06-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20180616_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postImage',
            field=models.ImageField(blank=True, null=True, upload_to='mainapp/static/photos'),
        ),
    ]
