# Generated by Django 2.0.2 on 2018-06-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20180616_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='passwd',
        ),
        migrations.AddField(
            model_name='post',
            name='isProtected',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
